### ISSUE TITLE
The API needs to be changed to tidy things up and fix mistakes

### ISSUE THREAD

**Issue by taye** [taye/interact.js#88]
The following problems should be addressed:

 - [x] #87 - *Settings like snap, inertia, etc. should be per-action*. PR #115
 - [ ] #84 - *Resize restriction is broken*. Partly fixed by per-action settings.
 - [x] #37 - *Resizing from top or left border disabled by default*. PR #145
 - [x] #94 - *Interactable methods like inertia, snap, restrict shouldn't have equivalent methods on the interact object*. Commit 3a3bc76
 - [x] #121 - *Need to unify grid, acnhor and path snapping*. PR #127.
 - [x] #122 - *Drop-related events shouldn't be InteractEvent objects*. Commit 2bb8b43
